### ISSUE TITLE
``pyenv install 3.5.6'' failed with :  ImportError: No module named 'math'

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1493]
Hi,

See the following error:

```
$ pyenv install 3.5.6
[...]
2019-12-18 16:17:35 (6.33 MB/s) - ‘/home/werner/.pyenv/cache/Python-3.5.6.tar.xz’ saved [15412832/15412832]

Installing Python-3.5.6...

BUILD FAILED (Ubuntu 19.10 using python-build 1.2.15-4-g089b828b)

Inspect or clean up the working tree at /tmp/python-build.20191218161735.29045
Results logged to /tmp/python-build.20191218161735.29122.log

Last 10 log lines:
  File "/tmp/python-build.20191218161735.29045/Python-3.5.6/Lib/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/tmp/python-build.20191218161735.29045/Python-3.5.6/Lib/ensurepip/__init__.py", line 5, in <module>
    import tempfile
  File "/tmp/python-build.20191218161735.29045/Python-3.5.6/Lib/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/tmp/python-build.20191218161735.29045/Python-3.5.6/Lib/random.py", line 41, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: No module named 'math'
make: *** [Makefile:1048: install] Error 1
```

Any hints for this issue?

**Comment by joshfriend** [comment]
Please provide the information requested in the issue template

**Comment by hongyi-zhao** [comment]
Platform information (e.g. Ubuntu Linux 16.04):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

OS architecture (e.g. amd64):

$ uname -a
Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

pyenv version:
$ pyenv --version
pyenv 1.2.15-2-g22c0202
Python version:
cpython 3.5.6
C Compiler information (e.g. gcc 7.3): 
$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0

**Comment by ms-lolo** [comment]
@hongyi-zhao were you able to find the solution to this? running into this same error on an ubuntu 18.04 server :(

**Comment by hongyi-zhao** [comment]
@ms-lolo I have just tried again and found that the problem has been solved, at least for the environment of mine. See following for the detailed environment info/steps used by me.

The OS info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```

The pyenv version:
```
$ git log | head -5
commit 806b30d6ce5b263a765648fbcdd68266833b7289
Author: Josh Friend <josh@fueledbycaffeine.com>
Date:   Thu Oct 8 20:59:02 2020 -0400

    v1.2.21
```

The steps to build the cpython 3.5.6:

```
$ sudo apt-get install libsqlite3-dev
$ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv-install 3.5.6
```

Regards,
HY

**Comment by sharefantasy** [comment]
@hongyi-zhao hi, did you find the solution now? I reproduce it in 3.6.3. thanks!

**Comment by hongyi-zhao** [comment]
@sharefantasy I can't reproduce the problem reported by you. Please see the details info in my scenario below:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

$ sudo apt-get install libsqlite3-dev
$ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.3
--2021-04-21 13:33:51--  https://mirrors.huaweicloud.com/python/3.6.3/Python-3.6.3.tar.xz
Resolving mirrors.huaweicloud.com (mirrors.huaweicloud.com)... 49.4.56.10, 49.4.56.13, 49.4.56.8
Connecting to mirrors.huaweicloud.com (mirrors.huaweicloud.com)|49.4.56.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16974296 (16M) [application/octet-stream]
Saving to: ‘/home/apollo/.pyenv/cache/Python-3.6.3.tar.xz’

/home/apollo/.pyenv/cache/Py 100%[============================================>]  16.19M  10.8MB/s    in 1.5s    

2021-04-21 13:33:53 (10.8 MB/s) - ‘/home/apollo/.pyenv/cache/Python-3.6.3.tar.xz’ saved [16974296/16974296]

Installing Python-3.6.3...
Installed Python-3.6.3 to /home/apollo/.pyenv/versions/3.6.3
```

**Comment by russellvt** [comment]
Rather annoying that @joshfriend keeps closing these issues with/without info... I see this A LOT on Cygwin, and expect it's some weird autoconf issue, or similar. But this is easily reproducible on any Cygwin64 platform (at least without the correct libraries installed, anyway)

**Comment by native-api** [comment]
@russellvt Without the necessary diagnostic info as per the issue template, we cannot diagnose the error thus cannot tell if this is a legit bug in Pyenv or a broken environment / bug in something else. So there's no point in keeping the issue open. As simple as that.

If you provide the neessary info, we'll reopen the issue if it's really a bug in Pyenv.

**Comment by joostlawerman** [comment]
Experiencing the same issue on OSX on each version I am trying to install. Below listed for `pyenv install 3.9.9`

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): OSX Montery - 12.0.1
- [x] OS architecture (e.g. amd64): arm64-apple-darwin21.1.0 (M1)
- [x] pyenv version: 2.2.2
- [x] Python version: 3.9.9
- [x] C Compiler information (e.g. gcc 7.3): 13.0.0
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/joostlawerman/b40d46a73b10f8e2c49cfb03f39d6024

**Comment by native-api** [comment]
@joostlawerman Yours is a duplicate of https://github.com/pyenv/pyenv/issues/2169 .

**Comment by basillatif** [comment]
Hi, all, I spent my entire morning working through pyenv installation issues. 

I ran into this exact same error. I fixed by by uninstalling and reinstalling pyenv. 

I ran `brew uninstall pyenv` followed by `brew install pyenv`

Good luck to everyone.

**Comment by tardunge** [comment]
@joostlawerman I'm facing the same error. Any luck?
I've tried using rosetta too, no luck. It happens for all universal binaries.

**Comment by hwiorn** [comment]
I got a same problem and I figured out the problem.
`math` module is a `.so` module.
`Import error` is that `pyenv` install can not compile python itself correctly.
If you can check out a result log such as `/tmp/python-build.XXXXXXXX.XXXX.log`, you will find what the cause is.

```
Traceback (most recent call last):
  File "/tmp/python-build.20220218121327.1245650/Python-3.9.2/Lib/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/tmp/python-build.20220218121327.1245650/Python-3.9.2/Lib/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/tmp/python-build.20220218121327.1245650/Python-3.9.2/Lib/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/tmp/python-build.20220218121327.1245650/Python-3.9.2/Lib/ensurepip/__init__.py", line 5, in <module>
    import tempfile
  File "/tmp/python-build.20220218121327.1245650/Python-3.9.2/Lib/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/tmp/python-build.20220218121327.1245650/Python-3.9.2/Lib/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
make: *** [Makefile:1255: install] Error 1
```

If you scroll further up, you can find modules which are failed to build.
```
...

Failed to build these modules:
...
cmath                 fcntl                 grp                
math                  mmap                  nis                
ossaudiodev           parser                pyexpat            
... 
```

Scroll up a bit more and you'll find what the error is.

```
...
/home/timlee/anaconda3/bin/x86_64-conda-linux-gnu-cc -pthread -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/timlee/anaconda3/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/timlee/anaconda3/include -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -I./Include -I. -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/tmp/python-build.20220218121327.1245650/Python-3.9.2/Include -I/tmp/python-build.20220218121327.1245650/Python-3.9.2 -c /tmp/python-build.20220218121327.1245650/Python-3.9.2/Modules/_pickle.c -o build/temp.linux-x86_64-3.9/tmp/python-build.20220218121327.1245650/Python-3.9.2/Modules/_pickle.o -DPy_BUILD_CORE_MODULE
In file included from /home/timlee/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/include/features.h:375,
                 from /home/timlee/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/include/limits.h:26,
                 from /home/timlee/anaconda3/lib/gcc/x86_64-conda-linux-gnu/9.3.0/include-fixed/limits.h:194,
                 from /home/timlee/anaconda3/lib/gcc/x86_64-conda-linux-gnu/9.3.0/include-fixed/syslimits.h:7,
                 from /home/timlee/anaconda3/lib/gcc/x86_64-conda-linux-gnu/9.3.0/include-fixed/limits.h:34,  
                 from ./Include/Python.h:11,
                 from /tmp/python-build.20220218121327.1245650/Python-3.9.2/Modules/arraymodule.c:7:
/usr/include/x86_64-linux-gnu/sys/cdefs.h:492:49: error: missing binary operator before token "("
  492 | #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)
      |                                                 ^
In file included from /home/timlee/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/include/features.h:375,
                 from /home/timlee/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/include/limits.h:26,
                 from /home/timlee/anaconda3/lib/gcc/x86_64-conda-linux-gnu/9.3.0/include-fixed/limits.h:194,
                 from /home/timlee/anaconda3/lib/gcc/x86_64-conda-linux-gnu/9.3.0/include-fixed/syslimits.h:7,
                 from /home/timlee/anaconda3/lib/gcc/x86_64-conda-linux-gnu/9.3.0/include-fixed/limits.h:34,
                 from ./Include/Python.h:11,
                 from /tmp/python-build.20220218121327.1245650/Python-3.9.2/Modules/cmathmodule.c:5:
/usr/include/x86_64-linux-gnu/sys/cdefs.h:492:49: error: missing binary operator before token "("
  492 | #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)   
      |                                                 ^
In file included from ./Include/Python.h:25,
                 from /tmp/python-build.20220218121327.1245650/Python-3.9.2/Modules/cmathmodule.c:5:
/home/timlee/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/include/stdio.h:46:22: error: expected ';' before 'typedef'
   46 | __BEGIN_NAMESPACE_STD    
      |                      ^  
      |                      ;
   47 | /* The opaque type of streams.  This is the definition used elsewhere.  */
   48 | typedef struct _IO_FILE FILE;
      | ~~~~~~~            
...
```
I found my anaconda-gcc(9.3.0) didn't compile cpython 3.9.2. I disabled the anaconda temporarily. And I can build and pyenv-install it using system gcc(9.3.0). 

I think different compiler environment(e.g.: clang path, anaconda-gcc) can cause this issue.
I hope this helps.

**Comment by native-api** [comment]
@markfaine 3.6.8 is EOL.
Try 3.6.15 (or simply 3.6 which will [resolve](https://github.com/pyenv/pyenv/blob/master/README.md#prefix-auto-resolution-to-the-latest-version) to it) which has user-provided downstream patches.

If you're interested in using 3.6.8 specifically, we can accept a fix (most probably, backporting those same downstream patches).

**Comment by markfaine** [comment]
> [@markfaine](https://github.com/markfaine) 3.6.8 is EOL. Try 3.6.15 (or simply 3.6 which will [resolve](https://github.com/pyenv/pyenv/blob/master/README.md#prefix-auto-resolution-to-the-latest-version) to it) which has user-provided downstream patches.
> 
> If you're interested in using 3.6.8 specifically, we can accept a fix (most probably, backporting those same downstream patches).

This might be good enough.  I just need to be compatible with out of the box RHEL8 platform-python.

It did do a lot of patches before attempting to install but it still fails:

```

BUILD FAILED (Ubuntu 25.04 using python-build 2.6.0)

Inspect or clean up the working tree at /tmp/python-build.20250601125016.13499
Results logged to /tmp/python-build.20250601125016.13499.log

Last 10 log lines:
  File "/tmp/python-build.20250601125016.13499/Python-3.6.15/Lib/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/tmp/python-build.20250601125016.13499/Python-3.6.15/Lib/ensurepip/__init__.py", line 5, in <module>
    import tempfile
  File "/tmp/python-build.20250601125016.13499/Python-3.6.15/Lib/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/tmp/python-build.20250601125016.13499/Python-3.6.15/Lib/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
make: *** [Makefile:1102: install] Error 1
```

**Comment by litoj** [comment]
Hi, I'm facing the exact same issue for 3.5 and 3.6. I need to install python 3.5 because some package we need to use for a project uses packages available only in this old version. I installed pyenv using pacman, but it throws out the math error for everything under 3.7.

[python-build.20250622114342.133389.log](https://github.com/user-attachments/files/20852041/python-build.20250622114342.133389.log)

**Comment by native-api** [comment]
@litoj Fixed in https://github.com/pyenv/pyenv/pull/3280

**Comment by native-api** [comment]
I'm opening a discussion why people keep using non-last EOL micro releases without downstream patches -- because I don't quite understand,
[Backport downstream patches for EOL versions to non-last releases? · pyenv · Discussion #3299](https://github.com/orgs/pyenv/discussions/3299)
